kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-manager-uyxsh

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-manager-uyxsh
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["chaos-mesh.org"]
    resources: [ "*" ]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-manager-uyxsh
  namespace: default
subjects:
  - kind: ServiceAccount
    name: account-default-manager-uyxsh
    namespace: default
roleRef:
  kind: Role
  name: role-default-manager-uyxsh
  apiGroup: rbac.authorization.k8s.io
