kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: hlab
  name: account-cluster-manager-rxanv

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cluster-manager-rxanv
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["chaos-mesh.org"]
    resources: [ "*" ]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-manager-rxanv
subjects:
  - kind: ServiceAccount
    name: account-cluster-manager-rxanv
    namespace: hlab
roleRef:
  kind: ClusterRole
  name: role-cluster-manager-rxanv
  apiGroup: rbac.authorization.k8s.io
