{{- if .Values.cm.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-cm
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.cm.config }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
